services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ethosview-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ethosview-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Go Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ethosview-backend
    environment:
      # Supabase Database Configuration
      - DB_HOST=aws-1-us-east-2.pooler.supabase.com
      - DB_PORT=5432
      - DB_USER=postgres.wrxyobquvqbwuinlikur
      - DB_PASSWORD=Dragonbobby20
      - DB_NAME=postgres
      - DB_SSL_MODE=require
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Application Configuration
      - PORT=8080
      - ENVIRONMENT=production
      # Supabase Configuration
      - SUPABASE_URL=https://wrxyobquvqbwuinlikur.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyeHlvYnF1dnFid3Vpbmxpa3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTc1MDksImV4cCI6MjA3MzI3MzUwOX0.irO5qSxvXyViVvXyp_1Nn3vLIqNb9oWk4LXJ53d86n4
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyeHlvYnF1dnFid3Vpbmxpa3VyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImiYXQiOjE3NTc2OTc1MDksImV4cCI6MjA3MzI3MzUwOX0.-AxeaFMN7lYl3Bi4wbjC9-xWICLUrMf06xHZpb2MoKc
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ethosview-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend
  frontend:
    build:
      context: ./ethosview-frontend
      dockerfile: Dockerfile
    container_name: ethosview-frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
      - INTERNAL_API_BASE_URL=http://backend:8080
      - NEXT_PUBLIC_SUPABASE_URL=https://wrxyobquvqbwuinlikur.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyeHlvYnF1dnFid3Vpbmxpa3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTc1MDksImV4cCI6MjA3MzI3MzUwOX0.irO5qSxvXyViVvXyp_1Nn3vLIqNb9oWk4LXJ53d86n4
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ethosview-network

volumes:
  redis_data:

networks:
  ethosview-network:
    driver: bridge
